instruments:
  cello:
    program_number: 42
    pitch_range: ["c2", "a5"]
  contrabass:
    program_number: 43
    # Technical top of range is 74, but that is not bassy at all
    pitch_range: ["e1", "a2"]
  choir_aahs:
    program_number: 52
    pitch_range: ["c4", "c6"]
  electric_bass_picked:
    program_number: 35
    pitch_range: ["e1", "d#4"]
  electric_guitar_distorted:
    program_number: 30
    pitch_range: ["e2", "d6"]
  english_horn:
    program_number: 69
    pitch_range: ["e3", "a5"]
queries:
  cpu:
    query: |
      1 - avg(rate(node_cpu_seconds_total{job="node", mode="idle", instance="$instance"}[30s]))
    instrument: cello
  ram:
    query: |
      1 - (
        avg(node_memory_MemAvailable_bytes{job="node", instance="$instance"})
        /
        avg(node_memory_MemTotal_bytes{job="node", instance="$instance"})
      )
    instrument: contrabass
  procs:
    query: |
      avg_over_time(node_procs_running{job="node", instance="$instance"}[30s])
      /
      max_over_time(node_procs_running{job="node", instance="$instance"}[10m])
    instrument: english_horn
scale:
  # One of the scale classes in music21.scale:
  # https://web.mit.edu/music21/doc/moduleReference/moduleScale.html
  class: MajorScale
  tonic: c
